name: 2 - Release to homolog

on:
  push:
    branches:
      - develop

env:
  CURRENT_VERSION: ${{ github.ref_name }}

jobs:
  build:
    name: Build Homolog base image
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout to develop
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build image
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}
        run: |
          FILE=$(git diff --name-only origin/develop -- poetry.lock Dockerfile HEAD -- poetry.lock Dockerfile )
          echo $FILE
          if [ "$FILE" == "" ]; then
            echo "Imagem Atualizada!"
          else
            docker login ghcr.io -u ${{ secrets.GHCR_USER }} -p ${{ secrets.GHCR_TOKEN }}
            docker build . -t ghcr.io/cavalheirodev/actions-poc-base:homolog
            docker tag ghcr.io/cavalheirodev/actions-poc-base:homolog ghcr.io/cavalheirodev/actions-poc-base:test
            docker push ghcr.io/cavalheirodev/actions-poc-base:homolog
            docker push ghcr.io/cavalheirodev/actions-poc-base:test
          fi;

  deploy:
    name: Deploy to Homolog
    runs-on: self-hosted
    needs: build
    container:
      image: ghcr.io/cavalheirodev/actions-poc-base:homolog
      credentials:
        username: ${{ secrets.GHCR_USER }}
        password: ${{ secrets.GHCR_TOKEN }}
    steps:
      - name: Checkout to develop
        uses: actions/checkout@v4

      - name: Deploy app
        run: python main.py
