name: 3 - Release to production (Manual)

on:
  workflow_dispatch:

env:
  CURRENT_VERSION: ${{ github.ref_name }}


jobs:
  verify:
    defaults:
      run:
        shell: bash

    name: Checando tags
    runs-on: ubuntu-latest
    steps:
      - name: Erro - Tag invalida
        if: ${{ github.ref_type != 'tag' }}
        run: |
          echo "Por favor selecione uma tag para fazer o deploy!"
          exit 1
      
      - name: Verificação concluida com sucesso!
        if: ${{ github.ref_type == 'tag' }}
        run: |
          echo "Tag selecionada com sucesso! Iniciando processo de deploy."

  build:
    name: Build base image
    runs-on: self-hosted
    needs: verify
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout to Tag
        uses: actions/checkout@v4

      - name: Build image
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}
        run: |
          docker build . -t ghcr.io/cavalheirodev/actions-poc-base:main
          docker push ghcr.io/cavalheirodev/actions-poc-base:main

  deploy:
    name: Deploy to Production
    runs-on: self-hosted
    needs: build
    container:
      image: ghcr.io/cavalheirodev/actions-poc-base:main
      credentials:
        username: ${{ secrets.GHCR_USER }}
        password: ${{ secrets.GHCR_TOKEN }}
    steps:
      - name: Checkout to Tag
        uses: actions/checkout@v4

      - name: Deploy app
        run: python main.py