name: New Release

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  release:
    name: Create New Release
    runs-on: self-hosted
    if: github.event.pull_request.merged == true
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout to Main
        uses: actions/checkout@v4

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}
        with:
          tag_name: ${{ github.event.pull_request.title }}
          release_name: ${{ github.event.pull_request.title }}
          body_path: ./CHANGELOG.md
          draft: false
          prerelease: false
    
  build:
    name: Build base image
    runs-on: self-hosted
    if: github.event.pull_request.merged == true
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout to Main
        uses: actions/checkout@v4

      - name: Build image
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}
        run: |
          docker build . --file dockerfiles/Dockerfile_Base --tag ghcr.io/cavalheirodev/actions-poc-base:main
          docker push ghcr.io/cavalheirodev/actions-poc-base:main