name: New Release

on:
  pull_request:
    branches: [main]
    types: [closed]

env:
  MASTER_DEPLOY_KEY: ${{ secrets.MASTER_DEPLOY_KEY }}

jobs:
  release:
    if: github.event.pull_request.merged == true
    defaults:
      run:
        shell: bash

    name: Create New Release
    runs-on: self-hosted
    steps:
      - name: Checkout to Main
        uses: actions/checkout@v4

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.event.pull_request.title }}
          release_name: ${{ github.event.pull_request.title }}
          body_path: ./CHANGELOG.md
          draft: false
          prerelease: false
