name: Release to production (Manual)

on:
  workflow_dispatch:


jobs:
  verify:
    defaults:
      run:
        shell: bash

    name: Checando tags...
    runs-on: ubuntu-latest
    steps:
      - name: Erro - Tag invalida
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: |
          echo "Por favor selecione uma tag para fazer o deploy!"
          exit 1
      
      - name: Verificação concluida com sucesso!
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          echo "Tag selecionada com sucesso! Iniciando processo de deploy."

build:
  
