name: 1 - Tests

on:
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize", "ready_for_review"]

jobs:
  build:
    name: Build base image
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    outputs:
      test_image: ${{ steps.set-output.outputs.test_image }}
    steps:
      - name: Checkout to Tag
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build image
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}
        id: set_output
        run: |
          FILE=$(git diff --name-only origin/develop -- poetry.lock Dockerfile HEAD -- poetry.lock Dockerfile )
          echo $FILE
          if [ "$FILE" == "" ]; then
            TEST_IMAGE="ghcr.io/cavalheirodev/actions-poc-base:test"
            echo "Imagem Atualizada! Usando imagem padrão: $TEST_IMAGE"
          else
            docker login ghcr.io -u ${{ secrets.GHCR_USER }} -p ${{ secrets.GHCR_TOKEN }}
            docker build . -t ghcr.io/cavalheirodev/actions-poc-base:test-temp
            docker push ghcr.io/cavalheirodev/actions-poc-base:test-temp
            TEST_IMAGE="ghcr.io/cavalheirodev/actions-poc-base:test-temp"
            echo "Imagem Atualizada! Nova imagem criada: $TEST_IMAGE"
          fi;
          echo "TEST_IMAGE=${TEST_IMAGE}" >> $GITHUB_ENV

  test:
    defaults:
      run:
        shell: bash
    name: Testando Aplicação
    runs-on: ubuntu-latest
    needs: build
    container:
      image: ${{ env.TEST_IMAGE }}
      credentials:
        username: ${{ secrets.GHCR_USER }}
        password: ${{ secrets.GHCR_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Running Test
        run: |
          IMAGE_NAME="${{ env.TEST_IMAGE }}"
          echo "Rodando testes na imagem: $IMAGE_NAME"
          python main.py
