name: 1 - Tests

on:
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize", "ready_for_review"]

jobs:
  build:
    name: Build base image
    runs-on: ubuntu-latest
    needs: verify
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout to Tag
        uses: actions/checkout@v4

      - name: Build image
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}
        run: |
          docker login ghcr.io -u ${{ secrets.GHCR_USER }} -p ${{ secrets.GHCR_TOKEN }}
          docker build . -t ghcr.io/cavalheirodev/actions-poc-base:test
          docker push ghcr.io/cavalheirodev/actions-poc-base:test

  test:
    defaults:
      run:
        shell: bash
    name: Testando Aplicação
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cavalheirodev/actions-poc-base:test
      credentials:
        username: ${{ secrets.GHCR_USER }}
        password: ${{ secrets.GHCR_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Poetry
        run: |
          pip install poetry
          poetry config virtualenvs.create false

      - name: Install dependencies
        run: |
          poetry export -f requirements.txt -o requirements.txt --without-hashes
          pip uninstall poetry -y
          pip install -r requirements.txt

      - name: Running Test
        run: |
          echo "Rodando testes..."
          python main.py
